name: rmpl_hrm
description: RMPL HRM App and Software
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  calendar_date_picker2: ^0.5.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get: ^4.6.6
  loading_indicator: ^3.1.1
  swipe_to_complete: ^0.0.1
  syncfusion_flutter_charts: ^23.1.39
  table_calendar: ^3.0.9
  velocity_x: ^4.1.1

  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.13.0
  formz: ^0.6.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
